Pipe tools
codilime/contrail-windows-tools pull request #1
Opened 2017-05-22 11:26 UTC by jablonskim

2017-05-23 13:02 UTC, m-kostrzewa requested changes
Pretty nice code.

I haven't commented everywhere, where `const` should be used, but consider adding it wherever you can.

2017-05-23 13:02 UTC, m-kostrzewa commented on Common/utils.cpp
> +         throw std::runtime_error("Error converting string: " + Utils::GetFormattedWindowsErrorMsg());
Memory leak here on `wide_name` if exception is thrown.

2017-05-23 13:02 UTC, m-kostrzewa commented on PipeTestTool/pipetesttool.cpp
> +    HANDLE handle = CreateFile(pipe_name, access_flags, 0, NULL, attrs, flags, NULL);
I think we should make all these variables const

2017-05-23 13:02 UTC, m-kostrzewa commented on PipeTestTool/PipeTestTool.qbs
> +    cpp.cxxLanguageVersion: "c++14"
Does it build on 11? If so, I think we should downgrade

2017-05-23 13:02 UTC, m-kostrzewa commented on PipeTestTool/pipetesttool.cpp
> +        size_t len = echo_len - headers_len;
`headers_len` and `len` should be const I think

2017-05-23 13:02 UTC, m-kostrzewa commented on PipeTestTool/pipetesttool.h
> +        auto size = sizeof(data);
Should be const

2017-05-23 13:02 UTC, m-kostrzewa commented on SimplePipeMitmTool/pipemitmtool.cpp
> +    writing = false;
Shouldn't `writing` be std::atomic? Or are we not concerned with data races?

2017-05-23 15:58 UTC, jablonskim commented on SimplePipeMitmTool/pipemitmtool.cpp
> +    writing = false;
It's single-threaded application

2017-05-24 06:07 UTC, m-kostrzewa commented on SimplePipeMitmTool/pipemitmtool.cpp
> +    writing = false;
I thought asio handlers could be executed in parallel, but apparently not  https://stackoverflow.com/questions/16066007/does-boost-asio-call-async-handlers-sequentially

2017-05-24 09:17 UTC, m-kostrzewa approved these changes

2017-05-24 09:25 UTC, merged