Refactor
codilime/contrail-windows-tools pull request #107
Opened 2017-11-08 09:55 UTC by m-kostrzewa

2017-11-08 10:15 UTC, m-kostrzewa commented
Retest this please

2017-11-08 13:39 UTC, m-kostrzewa commented on CIScripts/Deployment/AnsibleDeploy.ps1
> +        # TODO
@wurbanski @climebil TODO here

2017-11-08 13:39 UTC, m-kostrzewa commented on CIScripts/TestIntegrationCommon.ps1
> +    # TODO ^^^^^^^^^^^^^^
@wurbanski @climebil TODO here

2017-11-08 13:43 UTC, m-kostrzewa commented
Retest this please

2017-11-08 13:49 UTC, m-kostrzewa commented on CIScripts/TestIntegrationCommon.ps1
> +$Env:DEPLOY_METHOD = "Legacy"
This will be removed when jenkins jobs are updated

2017-11-08 14:50 UTC, m-kostrzewa commented
I launched pure tests from this and it passes (except the last command due to typo, but next commit fixed it) http://ci.wincontrail.codilime.com:8080/job/Wincontrail/job/mk-wip-new-testint/12/console

2017-11-08 14:52 UTC, m-kostrzewa commented on CIScripts/TestIntegrationCommon.ps1
> +    # TODO
@wurbanski @climebil TODO fyi

2017-11-08 18:41 UTC, kaweue requested changes

2017-11-08 18:41 UTC, PawelMarchewkaCodiLime commented on CIScripts/TestIntegrationCommon.ps1
> +$TestbedSessions = $null
Actually this initialization is not necessary.

2017-11-08 18:41 UTC, PawelMarchewkaCodiLime commented on CIScripts/TestIntegrationCommon.ps1
> +    $TestbedSessions = New-RemoteSessions -VMNames $IPs -Credentials $Creds
$Creds is not set up.

2017-11-08 18:41 UTC, PawelMarchewkaCodiLime commented on CIScripts/RunTests.ps1
> +        return #just for test
Just to block merge :) I please revert this patch.

2017-11-08 18:41 UTC, PawelMarchewkaCodiLime commented on CIScripts/TestIntegrationCommon.ps1
> +    Write-Output "Won't run tests."
Why not Write-Host ?

2017-11-09 10:06 UTC, mclapinski submitted a review, later dismissed

2017-11-09 10:06 UTC, mclapinski commented on CIScripts/TestIntegrationCommon.ps1
> +$Env:SHOULD_RUN_TESTS = $true
Do you mean that this env will be set up by Jenkins? If yes then it's a very bad idea.

This shouldn't be an env var but a parameter set up by scripts and then passed forward.

2017-11-10 15:57 UTC, kaweue requested changes

2017-11-10 15:57 UTC, PawelMarchewkaCodiLime commented on CIScripts/Common/Aliases.ps1
> +$AccelPSCredentialT::add("PSCredentialT", "System.Management.Automation.PSCredential")
Missing new line at the end of file

2017-11-10 15:57 UTC, PawelMarchewkaCodiLime commented on CIScripts/TestIntegration.ps1
> +. $PSScriptRoot\Teardown.ps1
New line at the end of line

2017-11-10 16:49 UTC, jacek-izykowski submitted a review, later dismissed

2017-11-13 09:44 UTC, m-kostrzewa commented
Retest this please

2017-11-13 13:09 UTC, m-kostrzewa commented
Retest this please

2017-11-14 10:10 UTC, kaweue approved these changes

2017-11-14 10:11 UTC, jacek-izykowski approved these changes

2017-11-14 10:13 UTC, merged