JW-442 : Added tests for windows-linux integration
codilime/contrail-windows-tools pull request #120
Opened 2017-11-22 16:35 UTC by PawelMarchewkaCodiLime

2017-11-23 10:08 UTC, PawelMarchewkaCodiLime commented on CIScripts/Test/Tests/WindowsLinuxIntegrationTests.ps1
> +    #TODO:Remove
Remove this before merge

2017-11-24 11:21 UTC, jablonskim requested changes

2017-11-24 11:21 UTC, jablonskim commented on CIScripts/Test/Tests/WindowsLinuxIntegrationTests.ps1
> +    #TODO:Remove
+1

2017-11-24 11:40 UTC, katrybacka submitted a review, later dismissed

2017-11-24 14:17 UTC, katrybacka approved these changes

2017-11-24 14:20 UTC, jablonskim approved these changes

2017-11-27 09:22 UTC, merged