JW-867: MultiEnableDisableExtension Test
codilime/contrail-windows-tools pull request #18
Opened 2017-07-13 12:29 UTC by jablonskim

2017-07-14 11:34 UTC, mclapinski requested changes

2017-07-14 11:34 UTC, michal-clapinski commented on CIScripts/Tests/MultiEnableDisableExtensionTest.ps1
> +        Start-Sleep -s 1
Remove the sleeps.

2017-07-14 13:33 UTC, mgreg0r submitted a review, later dismissed

2017-07-14 13:36 UTC, mclapinski submitted a review, later dismissed

2017-07-15 02:18 UTC, m-kostrzewa commented on CIScripts/Tests/MultiEnableDisableExtensionTest.ps1
> +    foreach ($I in 1..$EnableDisableCount) {
This would fit better:
```
1..$EnableDisableCount | %{ do stuff }
```

2017-07-17 14:51 UTC, mclapinski approved these changes

2017-07-17 15:11 UTC, merged