JW-870: TCP over MPLS over GRE test
codilime/contrail-windows-tools pull request #25
Opened 2017-07-20 08:56 UTC by jablonskim

2017-07-21 16:15 UTC, mclapinski submitted a review, later dismissed
Same comments as from the other review apply!

2017-07-21 16:39 UTC, mgreg0r requested changes

2017-07-21 16:39 UTC, mgreg0r commented on CIScripts/Tests/TCPoMPLSoGRETest.ps1
> +    $ClientID = Invoke-Command -Session $Session2 -ScriptBlock { docker run --network $Using:NetworkName -d microsoft/nanoserver ping -t localhost }
Why are we pinging localhost in a TCP test? I think it should be replaced by some other command that doesn't run continuously

2017-07-24 10:02 UTC, mgreg0r submitted a review, later dismissed

2017-07-27 09:29 UTC, mgreg0r approved these changes

2017-07-27 09:32 UTC, merged