JW-883: Setting up network interfaces for containers in testbed
codilime/contrail-windows-tools pull request #29
Opened 2017-07-24 10:42 UTC by jacek-izykowski

2017-07-24 11:25 UTC, jablonskim requested changes

2017-07-24 11:25 UTC, jablonskim commented on TestbedScripts/TestEnvUtils.ps1
> +    $mac = docker exec $ContainerName powershell -Command {
First letter of variable name should be uppercase (`Mac` instead of `mac`)

2017-07-24 11:25 UTC, jablonskim commented on TestbedScripts/TestEnvUtils.ps1
> +        (Get-NetAdapter | Select-Object -first 1).macaddress
`first` should be `First` and `macaddress` should be `MacAddress`

2017-07-24 11:25 UTC, jablonskim commented on TestbedScripts/TestEnvUtils.ps1
> +    $command = ('$ifname = (Get-NetAdapter | Select-Object -first 1).Name; ' +`
Please change all first letter of variable names and parameters to uppercase.

2017-07-24 11:33 UTC, sodar requested changes

2017-07-24 11:33 UTC, sodar commented on TestbedScripts/TestEnvUtils.ps1
> +        '$ip_set_properly = (New-NetIPAddress -interfacealias ' +`
`ip_set_properly` name might be misleading. It could be named `ip_addresses_count`

2017-07-24 13:38 UTC, jablonskim approved these changes

2017-07-25 08:27 UTC, sodar approved these changes

2017-07-25 08:47 UTC, merged