JW-881: Multi-branch build
codilime/contrail-windows-tools pull request #31
Opened 2017-07-27 09:17 UTC by jablonskim

2017-07-28 08:46 UTC, m-kostrzewa submitted a review, later dismissed

2017-08-02 10:37 UTC, mclapinski requested changes

2017-08-02 10:37 UTC, michal-clapinski commented on CIScripts/BuildAgent.ps1
> +}
remove this

2017-08-02 10:57 UTC, mclapinski approved these changes

2017-08-02 14:09 UTC, m-kostrzewa requested changes
I disagree with previous @michal-clapinski 's request to remove
```
+$CustomBranches = @($Repos.Where({ $_.Branch -ne $_.DefaultBranch }) | Select-Object -ExpandProperty Branch -Unique)
+if ($CustomBranches.Count -gt 1) {
+    throw "Different custom branches defined for multiple repos"
+}
```

This behaviour is not supported and this snippet provides good debug msg

2017-08-02 14:11 UTC, m-kostrzewa approved these changes
nvm

2017-08-03 13:13 UTC, merged