[WIP] JW-943 Merge jobs
codilime/contrail-windows-tools pull request #38
Opened 2017-08-08 14:08 UTC by m-kostrzewa

2017-08-09 14:55 UTC, m-kostrzewa commented on CIScripts/BuildDockerDriver.ps1
> +go get -u -v $Env:DRIVER_SRC_PATH
I think this actually pulls from https://github.com/codilime/contrail-windows-docker. Furthermore, I think this builds only the master branch.

I suspect that only `go build` needs to be used here...

2017-08-14 13:34 UTC, jablonskim requested changes

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +}
Wrong indentation in this 2 lines

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +}
Wrong indentation in this 2 lines

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +}
Wrong indentation in lines above

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +function Clone-Repos {
Please use approved words in function names (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +function Contrail-Common-Actions {
Please use approved words in function names (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +function Sign-MSI {
Please use approved words in function names (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +function Build-DockerDriver {
Please use approved words in function names (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +function Build-Extension {
Please use approved words in function names (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)

2017-08-14 13:34 UTC, jablonskim commented on CIScripts/BuildFunctions.ps1
> +function Build-Agent {
Please use approved words in function names (https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)

2017-08-16 09:35 UTC, jablonskim submitted a review, later dismissed

2017-08-16 09:35 UTC, jablonskim commented on CIScripts/BuildAll.ps1
> +    [Repo]::new($Env:DRIVER_REPO_URL, $Env:DRIVER_BRANCH, "src/github.com/codilime/contrail-windows-docker" ,"master"),
Small formatting issue here (`" ,"` => `", "`).

2017-08-16 09:35 UTC, jablonskim commented on CIScripts/BuildDockerDriver.ps1
> +    [Repo]::new($Env:DRIVER_REPO_URL, $Env:DRIVER_BRANCH, "src/github.com/codilime/contrail-windows-docker" ,"master")
Small formatting issue here (`" ,"` => `", "`).

2017-08-16 09:40 UTC, jablonskim submitted a review, later dismissed

2017-08-16 10:07 UTC, jablonskim submitted a review, later dismissed

2017-08-17 09:38 UTC, Attil requested changes

2017-08-17 09:38 UTC, Attil commented on CIScripts/BuildFunctions.ps1
> +    Repo ([string] $Url, [string] $Branch, [string] $Dir, [string] $DefaultBranch) {
I think changing the order of parameters here to be consistent with the order of class fields would make the code easier to read. Or the other way around.

2017-08-17 09:38 UTC, Attil commented on CIScripts/BuildFunctions.ps1
> +    go get -u -v github.com/onsi/ginkgo/ginkgo
Are you sure we should always use the latest version of ginkgo?

2017-08-17 09:38 UTC, Attil commented on CIScripts/BuildFunctions.ps1
> +    go get -u -v github.com/mh-cbon/go-msi
Are you sure we should always use the latest version of Go MSI?

2017-08-17 09:57 UTC, katrybacka commented on CIScripts/BuildFunctions.ps1
> +    go get -u -v github.com/onsi/ginkgo/ginkgo
Yes

2017-08-17 09:57 UTC, katrybacka commented on CIScripts/BuildFunctions.ps1
> +    go get -u -v github.com/mh-cbon/go-msi
Yes

2017-08-17 10:00 UTC, Attil approved these changes

2017-08-17 10:04 UTC, jablonskim approved these changes

2017-08-17 10:05 UTC, merged