JW-1016 changed usage of vtest
codilime/contrail-windows-tools pull request #53
Opened 2017-08-29 11:09 UTC by michal-clapinski

2017-08-29 11:18 UTC, jablonskim submitted a review, later dismissed

2017-08-29 11:43 UTC, m-kostrzewa requested changes
A comment explaining that  vtest\all_tests_run.ps1 throws an exception instead of return code is important here, since all other tests just use $LASTEXITCODE. Other than that +1

2017-08-30 15:30 UTC, jablonskim approved these changes

2017-08-31 12:13 UTC, m-kostrzewa approved these changes

2017-08-31 14:50 UTC, merged