JW-1120: Fix abandoned mutex problem
codilime/contrail-windows-tools pull request #59
Opened 2017-09-06 14:44 UTC by jablonskim

2017-09-06 14:46 UTC, mclapinski submitted a review, later dismissed

2017-09-07 12:18 UTC, m-kostrzewa requested changes
To be extra safe:

I think we should also put `[void] $Mutex.WaitOne()` in try/catch. We should catch an `AbandonedMutexException`. https://msdn.microsoft.com/en-us/library/58195swd(v=vs.110).aspx

Also, how about we specify a timeout? https://msdn.microsoft.com/en-us/library/kzy257t0(v=vs.110).aspx Something like 10 minutes should be enough I think.

Here's what I envision in pseudocode
```
try {
  WaitOne(timeout=10mins)
  Connect-VIServer()
} except AbandonedMutexException {
  print a nice error msg
  not sure if it's possible to handle this here except bailing out
} finally {
  ReleaseMutex()
  CloseMutex()
}
```

2017-09-07 12:39 UTC, m-kostrzewa commented
https://msdn.microsoft.com/en-us/library/system.threading.abandonedmutexexception(v=vs.110).aspx

> The exception that is thrown when one thread acquires a Mutex object that another thread has abandoned by exiting without releasing it.

I guess this exception was thrown when the issue came up, but it wasn't being caught. let's add catching it for future-proofing

2017-09-08 10:19 UTC, m-kostrzewa approved these changes

2017-09-08 15:50 UTC, merged