JW-1006 Linked clone support for testbed VMs
codilime/contrail-windows-tools pull request #60
Opened 2017-09-07 13:12 UTC by pjrusak

It is using powered off VM placed in Templates folder as parent for spawned testbed. 
VM has to have snapshot which is used as base disk for child VMs disks. Possibly 
base snapshot could be set as another property in `NewVMCreationSettings` and be set 
from env variables in `SetCommonVariablesForNewVMsFromEnv.ps1`

2017-09-07 13:29 UTC, m-kostrzewa commented
Removed review request from Mateusz since he's got a pretty beefy task at hand.

2017-09-07 13:29 UTC, m-kostrzewa commented
I think @sodar looked into this task in the past, gonna add him

2017-09-07 13:36 UTC, m-kostrzewa requested changes
We also talked how the template is not converted to VM. Maybe we should detect if that's the case and convert it to VM inside the script?

2017-09-07 13:36 UTC, m-kostrzewa commented on CIScripts/VMUtils.ps1
> +        $BaseSnapshot = (Get-Snapshot -VM $Template)[0]
As we talked - `$BaseSnapshot` could be a parameter. But I personally think this is fine. However, maybe we should add an assert about length of array returned by `Get-Snapshot` to be 1?

2017-09-09 17:43 UTC, pjrusak commented
Janie, przetestuj proszę

2017-12-15 14:30 UTC, jacek-izykowski commented
CIScripts directory has been moved to a new repository:
https://github.com/codilime/contrail-windows-ci .

2017-12-15 14:30 UTC, closed without merging