JW-1129: Fix error message for SNAT test
codilime/contrail-windows-tools pull request #66
Opened 2017-09-18 10:15 UTC by jablonskim

2017-09-18 11:24 UTC, katrybacka requested changes

2017-09-18 11:24 UTC, katrybacka commented on CIScripts/Tests/SNATTest.ps1
> +            return $Res;
Please remove that semicolon

2017-09-18 13:56 UTC, sodar submitted a review, later dismissed

2017-09-18 14:06 UTC, katrybacka approved these changes

2017-09-19 08:40 UTC, jablonskim commented
Retest this please

2017-09-20 08:34 UTC, jablonskim commented
Retest this please

2017-09-20 09:58 UTC, merged