JW-450: Flow tests
codilime/contrail-windows-tools pull request #80
Opened 2017-10-02 13:13 UTC by jacek-izykowski

2017-10-05 08:39 UTC, jablonskim commented on CIScripts/Tests/VRouterAgentTests.ps1
> +        [Parameter(Mandatory = $true)] [string] $ContainerName,
Wrong indentation here and in some other functions

2017-10-05 10:08 UTC, jablonskim submitted a review, later dismissed

2017-10-05 14:13 UTC, jacek-izykowski commented
Janie, przetestuj, proszę.

2017-10-05 14:15 UTC, jacek-izykowski commented
Janie, przetestuj proszę.

2017-10-05 14:55 UTC, katrybacka requested changes

2017-10-05 14:55 UTC, katrybacka commented on CIScripts/Tests/VRouterAgentTests.ps1
> +        Start-Sleep -Seconds 2
please use constant values

2017-10-05 14:55 UTC, katrybacka commented on CIScripts/Tests/VRouterAgentTests.ps1
> +        $JobSender | Wait-Job -Timeout 5
same here

2017-10-05 14:55 UTC, katrybacka commented on CIScripts/Tests/VRouterAgentTests.ps1
> +        Start-Sleep -Seconds 5 # Wait for an update of flow table.
same here

2017-10-05 14:55 UTC, katrybacka commented on CIScripts/Tests/VRouterAgentTests.ps1
> +        Start-Sleep -Seconds 5 # Wait for an update of flow table.
same here

2017-10-05 14:55 UTC, katrybacka commented on CIScripts/Tests/VRouterAgentTests.ps1
> +        [Parameter(Mandatory = $true)] [string] $ContainerName,
Wrong indentation here

2017-10-05 14:55 UTC, katrybacka commented on CIScripts/Tests/VRouterAgentTests.ps1
> +            [Parameter(Mandatory = $true)] [TestConfiguration] $TestConfiguration)
Wrong indentation here

2017-10-05 15:38 UTC, katrybacka submitted a review, later dismissed

2017-10-09 07:30 UTC, jacek-izykowski commented
Janie, przetestuj proszę.

2017-10-09 09:11 UTC, jacek-izykowski commented
Janie, przetestuj proszę.

2017-10-09 10:05 UTC, jacek-izykowski commented
Janie, przetestuj proszę.

2017-10-09 10:54 UTC, jacek-izykowski commented
Janie, przetestuj proszę.

2017-10-09 15:59 UTC, katrybacka submitted a review, later dismissed

2017-10-10 11:56 UTC, jablonskim submitted a review, later dismissed

2017-10-10 13:57 UTC, jablonskim approved these changes

2017-10-10 14:57 UTC, merged