JW-1074 : Auto generate contrail-go-api types
codilime/contrail-windows-tools pull request #99
Opened 2017-10-31 09:03 UTC by PawelMarchewkaCodiLime

2017-10-31 09:05 UTC, PawelMarchewkaCodiLime commented
Retest this please

2017-10-31 09:29 UTC, PawelMarchewkaCodiLime commented
Retest this please

2017-10-31 10:15 UTC, PawelMarchewkaCodiLime commented
Retest this please

2017-11-03 12:01 UTC, jacek-izykowski submitted a review, later dismissed

2017-11-03 12:01 UTC, mclapinski requested changes

2017-11-03 12:01 UTC, michal-clapinski commented on CIScripts/BuildFunctions.ps1
> +
spaces

2017-11-06 09:34 UTC, mclapinski approved these changes

2017-11-06 09:41 UTC, merged